n = input('Digite algo e lhe direi sobre:')
print('O tipo primitivo desse valor é', type(n))
print('é composto somente de espaços? ', n.isspace())
print('é alfabético? ', n.isalpha())
print('é numérico? ', n.isnumeric())
print('é alfanumérico? ', n.isalnum())
print('está so em minusculos? ', n.islower())
print('está em maiusculas?', n.isupper())
print('está capitalizada? ', n.istitle())
